import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'

export default function Home() {
  const [serverVar, setServerVar] = useState(null)
  useEffect(() => {
    const effect = async () => {
      const result = await axios.get('api/hello')
      console.log(result)
      setServerVar(result.data.name)
    }
    effect()
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      { serverVar && <h1 className={styles.title}>
        Server variable = {serverVar}
      </h1>}
      <h1 className={styles.title}>
        Client variable = {process.env.NEXT_PUBLIC_CLIENT_VAR}
      </h1>

      </main>
    </div>
  )
}
